version: "3.6"

services:
  db:
    image: mysql
    platform: linux/amd64
    restart: always
    volumes:
      - ./seeds/dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: database
      MYSQL_DATABASE: database
      MYSQL_USER: database
      MYSQL_PASSWORD: database
    networks:
      - wp
    ports:
      - 3306:3306
      
  wordpress:
    depends_on:
      - db
    image: wordpress:php8.1
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: database
      WORDPRESS_DB_PASSWORD: database
      WORDPRESS_DB_NAME: database
      WORDPRESS_DEBUG: true
      WORDPRESS_TABLE_PREFIX: to_
    volumes:
      - ./wp-content:/var/www/html/wp-content
    ports:
      - 80:80
    networks:
      - wp

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: database
      MYSQL_USER: database
      MYSQL_PASSWORD: database
    networks:
      - wp

networks:
  wp:
volumes:
  frontend_data:
