# https://taskfile.dev

version: '3'

dotenv: ['.env', './.docker/.env', './.gitlab/.env']

tasks:
  default:
    cmds:
      - echo "Welcome in the {{.APP_TD}} project. Use task -l to print tasks details or task --list-all to list all tasks"
    silent: true

includes:
  app:
    taskfile: ./.docker/Taskfile.yml
    dir: ./.docker/src
  db:
    taskfile: ./.docker/tasks/Db.yml
  deploy:
    taskfile: ./.gitlab/Taskfile.yml
    dir: ./.gitlab
    optional: true
  yarn:
    taskfile: ./.docker/tasks/Yarn.yml
  composer:
    taskfile: ./.docker/tasks/Composer.yml
  pint:
    taskfile: ./.docker/tasks/Pint.yml
  artisan:
    taskfile: ./.docker/tasks/Artisan.yml
  wp:
    taskfile: ./.docker/tasks/Wp.yml
  elastic:
    taskfile: ./.docker/tasks/Elasticsearch.yml