name: Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install npm dependencies
        run: |
          npm install -g yarn
          cd wp-content/themes/tatoo
          yarn && yarn css

      - name: Deploy WordPress via SCP
        uses: appleboy/scp-action@v0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "~/public_html/subdomains/tatoo"
